name: henawi_limited
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  another_flushbar: ^1.12.30
  cupertino_icons: ^1.0.2
  dart_ping: ^9.0.1
  date_format: ^2.0.7
  easy_splash_screen: ^1.0.4
  flutter:
    sdk: flutter
  flutter_localization: ^0.1.13
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.7
  flutter_typeahead: ^4.7.0
  google_fonts: ^6.1.0
  intl: ^0.18.1
  pocketbase: ^0.15.1
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  syncfusion_flutter_charts: ^23.1.40

dev_dependencies:
  flutter_lints: ^2.0.0
  msix: ^3.16.4
  flutter_test:
    sdk: flutter

msix_config:
  display_name: Henawi Limited
  publisher_display_name: Henawi Limited Inc.
  identity_name: company.suite.flutterapp
  msix_version: 1.0.0.0
  capabilities: internetClient, location, systemManagement, pointOfService, screenDuplication,

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/images/logo-no-background.png
    - assets/images/logo-no-background1.png
    - assets/images/logo-color1.png
    - assets/images/perIMG.jpg
    - assets/images/profile.jpg
    - assets/images/blur.jpg
    - assets/icons/not-found.svg
    - assets/icons/exclamation.svg
